/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "HELLO": string;
    };
    "email": {
        "subject": string;
        "header": string;
        "success_mail": string;
        "error_mail": string;
    };
    "error": {
        "required": string;
        "unknown": string;
        "phone": string;
        "id": string;
        "type": string;
        "invalid": string;
        "range": string;
        "unique": string;
        "generic": string;
        "tooManyRequests": string;
        "database_issue": string;
        "unauthorized": string;
        "forbidden": string;
        "notFound": string;
        "conflict": string;
        "only": string;
        "string": {
            "email": string;
            "pattern": string;
            "length": string;
            "min": string;
            "max": string;
            "empty": string;
            "base": string;
            "uri": string;
        };
        "number": {
            "base": string;
            "min": string;
            "max": string;
            "pattern": string;
            "sign": {
                "positive": string;
                "negative": string;
            };
            "greater": string;
            "less": string;
        };
        "date": {
            "base": string;
            "iso": string;
            "javascript": string;
            "min": string;
            "max": string;
            "greater": string;
            "less": string;
        };
        "boolean": {
            "base": string;
        };
        "array": {
            "base": string;
            "min": string;
            "max": string;
            "length": string;
        };
        "object": {
            "base": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
