/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "HELLO": string;
    };
    "email": {
        "subject": string;
        "header": string;
        "success_mail": string;
        "error_mail": string;
    };
    "error": {
        "required": string;
        "unknown": string;
        "empty": string;
        "email": string;
        "phone": string;
        "id": string;
        "type": string;
        "length": string;
        "invalid": string;
        "pattern": string;
        "range": string;
        "unique": string;
        "min": string;
        "max": string;
        "generic": string;
        "tooManyRequests": string;
        "database_issue": string;
        "unauthorized": string;
        "forbidden": string;
        "notFound": string;
        "conflict": string;
        "only": string;
        "base": string;
        "number": {
            "base": string;
            "min": string;
            "max": string;
            "greater": string;
            "less": string;
        };
        "greater": string;
        "less": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
