/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "HELLO": string;
        "success_mail": string;
        "error_mail": string;
    };
    "error": {
        "required": string;
        "unknown": string;
        "empty": string;
        "email": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
